name: Expo Publish on Play Store
on:
  push:
    branches:
      - main
jobs:
  building:
    name: Install and building for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn install
      - run: expo build:android
  publishing:
    needs: [building]
    runs-on: ubuntu-latest
    steps:
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: expo upload:android --latest --key ${{ secrets.GOOGLE_SERVICES }}
    
