name: Expo Publish on Play Store
on:
  push:
    branches:
      - main
jobs:
  building:
    name: Install and building for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: eas build --platform android
  publishing:
    needs: [building]
    runs-on: ubuntu-latest
    steps:
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: eas submit -p android --latest --key=${{ secrets.GOOGLE_SERVICES }}
    
