name: Expo Deploy on Play Store
on:
  push:
    tags:
      - "v[0-9]*"
jobs:
  publishing:
    name: Build and upload on Play Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-cache: true
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - run: |
          yarn install
      - run: |
          yarn test --verbose
      - run: |
          expo build:android --type app-bundle > buildLogAndroid.txt
          cat buildLogAndroid.txt
      - run: |
          BUILD_ARTIFACT_URL=$(cat buildLogAndroid.txt | tail | egrep -o 'https?://expo\.io/artifacts/[^ ]+')
          echo "BUILD_ARTIFACT_URL=$BUILD_ARTIFACT_URL" >> $GITHUB_ENV
      - run: |
          echo "$GOOGLE_SERVICES" > key
          expo upload:android --type aab --track production --url ${{ env.BUILD_ARTIFACT_URL }} --key key
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
